@startuml
'https://plantuml.com/class-diagram

class ArrayList {
    int numRows
    getNumRows(): int
    setNumRows(int numRows): void
    rowCount(String fileName): int
    readToArray(): String[]
}

@enduml