@startuml
'https://plantuml.com/class-diagram

class ArrayList
{
    String text = ""
    getText(): String
    replace(String old, String str): void
    createFile(String name): void
    addString(String str): void
}

@enduml